version: '3'

services:
     app:
         build:
             context: web
             dockerfile: Dockerfile
         image: gpc_app
         ports:
            - 8082:80   
     api:
         build:
             context: api
             dockerfile: Dockerfile
         image: gpc_api
         ports:
            - 8083:8080
         volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
     notification:
          build:
            context: notification
            dockerfile: Dockerfile
          image: gpc_notification
          environment:
            - PORT=3005
            - DBCONNECTION=mongodb://administrador:qwertyui@192.168.200.89:27017/gpc?authSource=admin&readPreference=primary&ssl=false
            - SMS_DOMAIN=CLI_3275
            - SMS_LOGIN=isc.ventura@gmail.com
            - SMS_PASSWD=uy5988af
            - SMS_HOST=www.altiria.net
            - SMS_PORT=80
            - SMS_PATH=/api/http
            - SOCKET_HOST=http://192.168.200.89:8083/gpc/api/
          ports:
            - 3005:3005


