version: '3'

services:
     app:
         build:
             context: web
             dockerfile: Dockerfile
         image: gpc_app
         ports:
            - 8082:80
         volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"


